import {
  Russo_One,
  Open_Sans,
  Sankofa_Display,
  Saira,
  Tomorrow,
} from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});
const sankorika = Sankofa_Display({
  variable: "--font-sankorika",
  weight: ["400"],
  subsets: ["latin"],
});
const tomorrow = Tomorrow({
  variable: "--font-tomorrow",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

const saira = Saira({
  variable: "--font-sanira",
  subsets: ["latin"],
});

const russoOne = Russo_One({
  variable: "--font-russo-one",
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${tomorrow.variable} ${russoOne.variable} ${sankorika.variable}  ${saira.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
